/**
 * Baseten Chain Sandbox Communication
 * 
 * Handles communication with Baseten chains for plan generation and sandbox interaction.
 * Supports both portfolio chains and legacy single chains.
 * 
 * Usage:
 *   npx tsx src/baseten-chain-sandbox.ts --sandbox-id <id> --operation query
 *   npx tsx src/baseten-chain-sandbox.ts --specialty dev-router --payload '{"task": "test"}'
 */

import fetch from 'node-fetch';
import {
  SandboxChainRequest,
  SandboxChainResponse,
  ChainExecutionOptions,
  ChainExecutionResult,
  OrchestratorConfig,
  createLogger,
  sleep,
  retry,
} from './types.js';

const log = createLogger('baseten-chain-sandbox', process.env.VERBOSE === '1');

/** Baseten chain portfolio API client */
export class BasetenChainSandbox {
  private config: OrchestratorConfig;
  private baseUrl: string;
  private headers: Record<string, string>;

  constructor(config: OrchestratorConfig) {
    this.config = config;
    // Correct Baseten endpoint format for deployed models
    this.baseUrl = `https://model-${config.chainPortfolioId}.api.baseten.co/environments/production/sync`;
    this.headers = {
      'Authorization': `Api-Key ${config.basetenApiKey}`,
      'Content-Type': 'application/json',
      'Accept': 'application/json',
    };
  }

  /** Execute a chain request via the portfolio endpoint */
  async executeChain(options: ChainExecutionOptions): Promise<ChainExecutionResult> {
    const { specialty, input, timeout = 60000, dryRun = false } = options;
    
    if (dryRun || this.config.dryRun) {
      log.info('dry-run chain execution', { specialty, input });
      const task = input.task || 'feature implementation';
      const target = input.target || 'project';
      return {
        ok: true,
        executionId: `dry-run-${Date.now()}`,
        data: { specialty, input, dryRun: true },
        plan: `# Dry Run Plan: ${task}

## Target: ${target}

## Implementation Plan

### 1. Analyze Requirements
- [ ] Understand task: ${task}
- [ ] Review existing codebase in ${target}

### 2. Design Implementation
- [ ] Plan architecture and changes
- [ ] Identify files to modify

### 3. Implement Changes
- [ ] Write code in sandbox environment
- [ ] Follow project conventions

### 4. Test and Validate
- [ ] Run existing tests: \`npm test\`
- [ ] Add new tests for the feature
- [ ] Verify all tests pass
- [ ] Run linting and type checking

### 5. Commit and Create PR
- [ ] Create branch: feat/dry-run-${Date.now().toString(36)}
- [ ] Commit with descriptive message
- [ ] Push to remote
- [ ] Create PR with description

## Done When
- [ ] Feature fully implemented
- [ ] All tests passing
- [ ] Code committed on feature branch
- [ ] PR created
- [ ] Print OPENCODE_SDK_OK when finished

---

*Generated by Baseten Chain (dry-run)*
`,
      };
    }

    if (!this.config.basetenApiKey) {
      return { ok: false, error: 'BASETEN_API_KEY not configured' };
    }

    const portfolioId = options.portfolioId || this.config.chainPortfolioId;
    if (!portfolioId) {
      return { ok: false, error: 'Chain portfolio ID not configured' };
    }

    const url = `https://app.baseten.co/api/v1/models/${portfolioId}/predict`;
    
    // Build request payload based on the chain specialty
    const payload = this.buildChainPayload(specialty, input);
    
    log.verbose('Chain request', { url, specialty, payload });

    try {
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), timeout);

      const response = await fetch(url, {
        method: 'POST',
        headers: {
          ...this.headers,
          'X-Baseten-Chain-Specialty': specialty,
        },
        body: JSON.stringify(payload),
        signal: controller.signal,
      });

      clearTimeout(timeoutId);

      if (!response.ok) {
        const errorText = await response.text();
        log.error('Chain request failed', { status: response.status, error: errorText });
        return {
          ok: false,
          error: `HTTP ${response.status}: ${errorText}`,
        };
      }

      const result = await response.json() as Record<string, unknown>;
      log.verbose('Chain response', result);

      // Extract plan from response if available
      const plan = this.extractPlanFromResponse(result);
      
      return {
        ok: true,
        executionId: result.request_id as string || `exec-${Date.now()}`,
        data: result,
        plan,
      };
    } catch (err) {
      const error = err instanceof Error ? err.message : String(err);
      log.error('Chain execution error', error);
      return { ok: false, error };
    }
  }

  /** Communicate with a running sandbox via chain */
  async communicateWithSandbox(request: SandboxChainRequest): Promise<SandboxChainResponse> {
    const { 
      specialty, 
      sandboxId, 
      operation, 
      payload, 
      timeout = 30000,
      portfolioId = this.config.chainPortfolioId,
    } = request;

    if (this.config.dryRun) {
      log.info('dry-run sandbox communication', { sandboxId, operation });
      return {
        ok: true,
        sandboxState: {
          id: sandboxId,
          status: 'running',
          lastActivity: new Date().toISOString(),
        },
        data: { operation, payload, dryRun: true },
        timestamp: new Date().toISOString(),
      };
    }

    // Build chain input for sandbox communication
    const chainInput = {
      operation,
      sandbox_id: sandboxId,
      ...payload,
      _meta: {
        operation,
        sandbox_id: sandboxId,
        timestamp: new Date().toISOString(),
      },
    };

    log.info('Sandbox communication via chain', { sandboxId, operation, specialty });

    const chainResult = await retry(
      () => this.executeChain({
        specialty,
        input: chainInput,
        timeout,
      }),
      { attempts: 2, delay: 1000 }
    );

    if (!chainResult.ok) {
      return {
        ok: false,
        sandboxState: {
          id: sandboxId,
          status: 'error',
        },
        error: chainResult.error,
        timestamp: new Date().toISOString(),
      };
    }

    // Parse sandbox state from chain response
    const sandboxState = this.parseSandboxState(chainResult.data, sandboxId);
    
    return {
      ok: true,
      executionId: chainResult.executionId,
      sandboxState,
      data: chainResult.data,
      timestamp: new Date().toISOString(),
    };
  }

  /** Query sandbox status */
  async querySandboxStatus(sandboxId: string): Promise<SandboxChainResponse> {
    return this.communicateWithSandbox({
      specialty: 'dev-router',
      sandboxId,
      operation: 'query',
      payload: { status: true },
    });
  }

  /** Get sandbox logs */
  async getSandboxLogs(sandboxId: string, lines = 100): Promise<SandboxChainResponse> {
    return this.communicateWithSandbox({
      specialty: 'dev-router',
      sandboxId,
      operation: 'logs',
      payload: { lines },
    });
  }

  /** Pause sandbox */
  async pauseSandbox(sandboxId: string): Promise<SandboxChainResponse> {
    return this.communicateWithSandbox({
      specialty: 'dev-router',
      sandboxId,
      operation: 'pause',
      payload: {},
    });
  }

  /** Resume sandbox */
  async resumeSandbox(sandboxId: string): Promise<SandboxChainResponse> {
    return this.communicateWithSandbox({
      specialty: 'dev-router',
      sandboxId,
      operation: 'resume',
      payload: {},
    });
  }

  /** Monitor sandbox health */
  async monitorSandbox(sandboxId: string, interval = 10000): Promise<void> {
    log.info('Monitoring sandbox', { sandboxId, interval });
    
    while (true) {
      const status = await this.querySandboxStatus(sandboxId);
      
      if (!status.ok) {
        log.error('Sandbox monitoring failed', status.error);
        break;
      }

      const state = status.sandboxState;
      if (!state) {
        log.warn('No sandbox state in response');
        break;
      }

      log.info('Sandbox status', {
        id: state.id,
        status: state.status,
        url: state.url,
      });

      if (state.status === 'stopped' || state.status === 'error') {
        log.info('Sandbox stopped or errored, ending monitoring');
        break;
      }

      await sleep(interval);
    }
  }

  /** Build chain payload based on specialty */
  private buildChainPayload(specialty: string, input: Record<string, unknown>): Record<string, unknown> {
    // Map specialties to their expected input formats
    const specialtyMap: Record<string, (input: Record<string, unknown>) => Record<string, unknown>> = {
      'roadmap': (i) => ({
        request: i,
        specialty: 'roadmap',
        mode: 'execute',
      }),
      'opencode-agent-wiring': (i) => ({
        request: {
          task: i.task,
          target: i.target,
          context: i.context,
        },
        specialty: 'opencode-agent-wiring',
      }),
      'opencode-skill-scaffold': (i) => ({
        request: {
          skill_name: i.skill_name || i.skill,
          description: i.description,
          requirements: i.requirements,
        },
        specialty: 'opencode-skill-scaffold',
      }),
      'prd-daytona-execute': (i) => ({
        request: {
          plan_file: i.planFile || i.plan_file,
          branch: i.branch,
          task: i.task,
          target: i.target,
          provider: i.provider,
          operation: i.operation || 'execute',
        },
        specialty: 'prd-daytona-execute',
      }),
      'dev-router': (i) => ({
        request: i,
        specialty: 'dev-router',
      }),
      'default': (i) => ({
        request: i,
        specialty: specialty,
      }),
    };

    const builder = specialtyMap[specialty] || specialtyMap['default'];
    return builder(input);
  }

  /** Extract plan from chain response */
  private extractPlanFromResponse(result: Record<string, unknown>): string | undefined {
    // Try common plan fields
    const planFields = ['plan', 'roadmap', 'output', 'result', 'content', 'markdown'];
    
    for (const field of planFields) {
      if (result[field] && typeof result[field] === 'string') {
        return result[field] as string;
      }
      // Check nested in result.data
      if (result.data && typeof result.data === 'object') {
        const data = result.data as Record<string, unknown>;
        if (data[field] && typeof data[field] === 'string') {
          return data[field] as string;
        }
      }
    }

    // Check for roadmap phases
    if (result.phases && Array.isArray(result.phases)) {
      return result.phases.map((p: unknown) => {
        if (typeof p === 'string') return p;
        if (typeof p === 'object' && p !== null) {
          const phase = p as Record<string, unknown>;
          return `## ${phase.phase || phase.phase_id || 'Phase'}\n\n${phase.summary || phase.description || JSON.stringify(phase)}\n`;
        }
        return String(p);
      }).join('\n');
    }

    return undefined;
  }

  /** Parse sandbox state from chain response */
  private parseSandboxState(
    data: Record<string, unknown> | undefined,
    sandboxId: string
  ): SandboxChainResponse['sandboxState'] {
    if (!data) {
      return { id: sandboxId, status: 'error' };
    }

    // Extract from common response patterns
    const state = data.sandbox_state || data.sandbox || data.state || data;
    
    if (typeof state === 'object' && state !== null) {
      const s = state as Record<string, unknown>;
      return {
        id: (s.id || s.sandbox_id || sandboxId) as string,
        status: (s.status || s.state || 'unknown') as SandboxChainResponse['sandboxState']['status'],
        url: s.url as string | undefined,
        lastActivity: s.last_activity || s.lastActivity as string | undefined,
      };
    }

    return { id: sandboxId, status: 'unknown' };
  }
}

/** CLI entry point for standalone chain-sandbox communication */
async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const config = {
    chainPortfolioId: process.env.BASETEN_CHAIN_PORTFOLIO_ID || 'nwxlx5wy',
    basetenApiKey: process.env.BASETEN_API_KEY || '',
    dryRun: process.env.DRY_RUN === '1',
    verbose: process.env.VERBOSE === '1',
  } as OrchestratorConfig;

  const client = new BasetenChainSandbox(config);

  // Parse CLI args
  let sandboxId = '';
  let operation: SandboxChainRequest['operation'] = 'query';
  let specialty = 'dev-router';
  let payload: Record<string, unknown> = {};
  let timeout = 30000;
  let monitor = false;

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    switch (arg) {
      case '--sandbox-id':
        sandboxId = args[++i] || '';
        break;
      case '--operation':
        operation = (args[++i] || 'query') as SandboxChainRequest['operation'];
        break;
      case '--specialty':
        specialty = args[++i] || 'dev-router';
        break;
      case '--payload':
        try {
          payload = JSON.parse(args[++i] || '{}');
        } catch {
          payload = {};
        }
        break;
      case '--timeout':
        timeout = parseInt(args[++i] || '30000', 10);
        break;
      case '--monitor':
        monitor = true;
        break;
      case '--help':
      case '-h':
        console.log(`Usage: npx tsx baseten-chain-sandbox.ts [options]

Options:
  --sandbox-id <id>    Target sandbox ID
  --operation <op>     query|execute|monitor|health|logs|pause|resume
  --specialty <spec>   Chain specialty (default: dev-router)
  --payload <json>     JSON payload for the operation
  --timeout <ms>       Request timeout (default: 30000)
  --monitor            Continuous monitoring mode
  --help               Show this help`);
        process.exit(0);
    }
  }

  if (!sandboxId) {
    log.error('sandbox-id required');
    process.exit(1);
  }

  if (monitor) {
    await client.monitorSandbox(sandboxId);
    process.exit(0);
  }

  const response = await client.communicateWithSandbox({
    specialty,
    sandboxId,
    operation,
    payload,
    timeout,
  });

  console.log(JSON.stringify(response, null, 2));
  process.exit(response.ok ? 0 : 1);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch(err => {
    log.error('Fatal error', err instanceof Error ? err.message : String(err));
    process.exit(1);
  });
}

export default BasetenChainSandbox;
